### PR TITLE
No direct access

### PR DESCRIPTION
**Pull request by gnovaro**

### CODE REVIEW

**Comment by lenton** [comment]
All pull requests must target the `develop` branch, so I'm going to have to close this.

Also, this check is unnecessary since the Kohana website uses a `public` folder which means no classes are accessible directly. If the website ever upgraded to Kohana 3.4, these checks would all be removed anyway.

**Comment by enov** [comment]
@lenton I think this is good for merge.
- We are not enforcing to target the `develop` branch at this moment, only for case of the website, since http://staging.kohanaframework.org/ is down.
- This check is unnecessary, so removing it would be consistent with the official modules.
- This check will not be automatically removed away if we upgrade to Kohana 3.4, because it is in the `application` folder, it extends Kohana_Exception through the CFS.

**Comment by lenton** [comment]
> We are not enforcing to target the develop branch at this moment, only for case of the website, since http://staging.kohanaframework.org/ is down.

It seems to work for me.

> This check is unnecessary, so removing it would be consistent with the official modules.

He's adding it; not removing it.

> This check will not be automatically removed away if we upgrade to Kohana 3.4, because it is in the application folder, it extends Kohana_Exception through the CFS.

Part of the upgrading process for 3.4 would be to manually remove the direct access checks in user modules since it now ships a `public` folder.

**Comment by enov** [comment]
> He's adding it; not removing it.

lol... my bad :smile:

**Pull request closed without merging**
